// US Cities data - comprehensive list of major cities
export const US_CITIES = [
  "Montgomery, AL",
  "Mobile, AL",
  "Huntsville, AL",
  "Anchorage, AK",
  "Fairbanks, AK",
  "Juneau, AK",
  "Phoenix, AZ",
  "Tucson, AZ",
  "Mesa, AZ",
  "Chandler, AZ",
  "Little Rock, AR",
  "Fort Smith, AR",
  "Fayetteville, AR",
  "Los Angeles, CA",
  "San Diego, CA",
  "San Jose, CA",
  "San Francisco, CA",
  "Fresno, CA",
  "Sacramento, CA",
  "Long Beach, CA",
  "Oakland, CA",
  "Bakersfield, CA",
  "Anaheim, CA",
  "Denver, CO",
  "Colorado Springs, CO",
  "Aurora, CO",
  "Hartford, CT",
  "New Haven, CT",
  "Stamford, CT",
  "Wilmington, DE",
  "Dover, DE",
  "Jacksonville, FL",
  "Miami, FL",
  "Tampa, FL",
  "Orlando, FL",
  "St. Petersburg, FL",
  "Atlanta, GA",
  "Augusta, GA",
  "Columbus, GA",
  "Savannah, GA",
  "Honolulu, HI",
  "Boise, ID",
  "Chicago, IL",
  "Aurora, IL",
  "Naperville, IL",
  "Indianapolis, IN",
  "Fort Wayne, IN",
  "Des Moines, IA",
  "Cedar Rapids, IA",
  "Wichita, KS",
  "Overland Park, KS",
  "Louisville, KY",
  "Lexington, KY",
  "New Orleans, LA",
  "Baton Rouge, LA",
  "Portland, ME",
  "Baltimore, MD",
  "Boston, MA",
  "Worcester, MA",
  "Springfield, MA",
  "Detroit, MI",
  "Grand Rapids, MI",
  "Minneapolis, MN",
  "St. Paul, MN",
  "Jackson, MS",
  "Kansas City, MO",
  "St. Louis, MO",
  "Billings, MT",
  "Omaha, NE",
  "Lincoln, NE",
  "Las Vegas, NV",
  "Reno, NV",
  "Manchester, NH",
  "Newark, NJ",
  "Jersey City, NJ",
  "Albuquerque, NM",
  "New York, NY",
  "Buffalo, NY",
  "Rochester, NY",
  "Charlotte, NC",
  "Raleigh, NC",
  "Fargo, ND",
  "Columbus, OH",
  "Cleveland, OH",
  "Cincinnati, OH",
  "Oklahoma City, OK",
  "Tulsa, OK",
  "Portland, OR",
  "Eugene, OR",
  "Philadelphia, PA",
  "Pittsburgh, PA",
  "Providence, RI",
  "Charleston, SC",
  "Columbia, SC",
  "Sioux Falls, SD",
  "Memphis, TN",
  "Nashville, TN",
  "Houston, TX",
  "San Antonio, TX",
  "Dallas, TX",
  "Austin, TX",
  "Fort Worth, TX",
  "El Paso, TX",
  "Salt Lake City, UT",
  "Burlington, VT",
  "Virginia Beach, VA",
  "Norfolk, VA",
  "Richmond, VA",
  "Seattle, WA",
  "Spokane, WA",
  "Tacoma, WA",
  "Charleston, WV",
  "Milwaukee, WI",
  "Madison, WI",
  "Cheyenne, WY",
]

// US States data
export const US_STATES = [
  "Alabama",
  "Alaska",
  "Arizona",
  "Arkansas",
  "California",
  "Colorado",
  "Connecticut",
  "Delaware",
  "Florida",
  "Georgia",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  "North Carolina",
  "North Dakota",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Pennsylvania",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "Virginia",
  "Washington",
  "West Virginia",
  "Wisconsin",
  "Wyoming",
]

// Helper function to split array into N chunks
export function splitIntoChunks<T>(array: T[], numChunks: number): T[][] {
  const chunks: T[][] = Array.from({ length: numChunks }, () => [])
  
  array.forEach((item, index) => {
    chunks[index % numChunks].push(item)
  })
  
  return chunks
}
