#!/usr/bin/env bash
set -euo pipefail

ENV_FILE=".env.production"

VARS=(
  MONGODB_URI
  JWT_SECRET
  JWT_EXPIRES_IN
  STRIPE_SECRET_KEY
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
  STRIPE_PRODUCT_ID
  STRIPE_BASE_PRICE_ID
  STRIPE_WEBHOOK_SECRET
  NEXT_PUBLIC_APP_URL
  NEXT_PUBLIC_SITE_URL
  ODOO_URL
  ODOO_DB
  ODOO_USERNAME
  ODOO_API_KEY
  ODOO_COMPANY_NAME
  CLOUDINARY_CLOUD_NAME
  CLOUDINARY_API_KEY
  CLOUDINARY_API_SECRET
  GMAIL_USER
  GMAIL_APP_PASSWORD
  GTZSHIP_API_URL
  GTZSHIP_ACCESS_KEY
  GTZSHIP_USERNAME
  GTZSHIP_PASSWORD
  GTZSHIP_CUSTOMER_ID
  ADMIN_EMAIL
  ADMIN_NAME
  ADMIN_PASSWORD
)

if [ "$#" -gt 0 ]; then
  echo "Usage: $0"
  echo "This script reads required environment variables from the current shell and writes them into ${ENV_FILE}."
  exit 1
fi

missing=()
for name in "${VARS[@]}"; do
  if [ -z "${!name:-}" ]; then
    missing+=("$name")
  fi
 done

if [ "${#missing[@]}" -gt 0 ]; then
  echo "Error: missing required environment variables:" >&2
  for name in "${missing[@]}"; do
    echo "  - $name" >&2
  done
  echo "Please export the missing values before running this script." >&2
  exit 1
fi

escape_value() {
  local value="$1"
  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"
  value="${value//$'\n'/\\n}"
  printf '%s' "$value"
}

{
  echo "# Generated by scripts/setup-env-production.sh"
  echo "NODE_ENV=production"
  for name in "${VARS[@]}"; do
    value="${!name}"
    printf '%s="%s"\n' "$name" "$(escape_value "$value")"
  done
} > "$ENV_FILE"

chmod 600 "$ENV_FILE"
echo "${ENV_FILE} written successfully."
